### ISSUE TITLE
Not working with Sitecore 8.2

### ISSUE THREAD

**Issue by jacktinuss** [iamandycohen/UrlRewrite#23]
Hi Andy

From this documentation:
https://doc.sitecore.net/sitecore_experience_platform/developing/developing_with_sitecore/cache_api_changes

I can see that see that the cache api has changed in 8.2

Do you have any plans in implementing changes so the UrlRewrite module will work on 8.2?

Thanks in advance!

**Comment by iamandycohen** [comment]
You are correct.  A colleague of mine recently took the time to upgrade it
and I will integrate in the next week.

On Wed, Nov 2, 2016, 4:45 AM jacktinuss <notifications@github.com> wrote:

Hi Andy

From this documentation:
https://doc.sitecore.net/sitecore_experience_platform/developing/developing_with_sitecore/cache_api_changes

I can see that see that the cache api has changed in 8.2

Do you have any plans in implementing changes so the UrlRewrite module will
work on 8.2?

Thanks in advance!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iamandycohen/UrlRewrite/issues/23>, or mute the thread

**Comment by jacktinuss** [comment]
Nice, thanks a lot!

**Comment by iamandycohen** [comment]
Closed https://github.com/iamandycohen/UrlRewrite/releases/tag/v1.8.2
